'use strict';
// The bestiary: every creature of Duskwell with a large portrait, what it is and how to deal with it. A creature is
// entered when it first comes into view, and the list is kept with the save (G.seen).
const BESTIARY = [
  // ---- creatures
  { k: 'husk', area: 'hushvale', ar: ['الهيكل', 'قشرة فارغة بقي فيها بصيص نور. يجول، ثم يطاردك إذا رآك ويقفز عليك من قرب. اضربه حين يهبط.'], en: ['Husk', 'An empty shell with a spark still in it. It wanders, hunts you on sight and leaps when you are close. Strike it as it lands.'], s: 1.25 },
  { k: 'crawler', area: 'crossroads', ar: ['الزاحف', 'خنفساء مدرّعة بدرع مقطّع ووجه شاحب. تسير ذهاباً وإياباً وتطاردك إن رأتك. اضربها من الجانب فدرعها قاسٍ.'], en: ['Crawler', 'An armoured bug with a banded shell and a pale face. It paces back and forth and chases when it sees you.'] },
  { k: 'flyer', area: 'crossroads', ar: ['الطائر الشاحب', 'يرقة شاحبة بجناحين شفّافين وحلقات على جسمها. تحوم في الهواء وتنقضّ عليك.'], en: ['Pale Flyer', 'A pale larva with clear veined wings and a ringed body. It drifts through the air and dives at you.'] },
  { k: 'hopper', area: 'mossgrove', ar: ['القافز', 'كائن مستدير بقناع وقرون ظهرية وساقين قويتين. ينقبض لحظة ثم يقفز نحوك: تحرّك قبل أن يهبط.'], en: ['Hopper', 'A round masked creature with back spines and strong hind legs. It crouches, then leaps: move before it lands.'] },
  { k: 'spitter', area: 'mossgrove', ar: ['البصّاق', 'زهرة بفم مسنّن ولسان أحمر. تجمع بصاقها ثم تقذفه نحوك؛ ابقَ متحركاً وأسقطها بضربة.'], en: ['Spitter', 'A stalked bloom with a toothed maw. It gathers its spit, then flings it: keep moving.'] },
  { k: 'shard', area: 'crystal', ar: ['برج البلّور', 'عنقود بلّور حيّ بنواة مضيئة. يطلق شظايا ورديّة نحوك بعد وهجٍ قصير.'], en: ['Crystal Turret', 'A living crystal cluster with a glowing core. It fires pink shards after a short flare.'] },
  { k: 'sentinel', area: 'crossroads', ar: ['الحارس', 'حارس بدرع مجزّأ ووشاح ممزّق وسيف. تحمرّ عيناه قبل الضربة: تراجع أو اندفع خلفه.'], en: ['Sentinel', 'A guard in a banded carapace and a tattered tabard, with a sword. Its eyes turn red before it strikes.'] },
  { k: 'diver', area: 'crystal', ar: ['البعوضة', 'بعوضة مقنّعة ببطن مخطّط وخرطوم طويل. تقف لحظة ثم تنقضّ على موضعك.'], en: ['Diver', 'A masked mosquito with a striped abdomen and a long needle. It hovers, then dives where you stood.'] },
  { k: 'spider', area: 'webbed', ar: ['العنكبوت', 'عنكبوت مستدير يتدلّى من خيطه وينزل عليك. ثماني أرجل مفصّلة وفكّان وعيون صغيرة إضافية.'], en: ['Spider', 'A round spider that drops from its thread. Eight jointed legs, two fangs and a row of spare eyes.'] },
  { k: 'shroom', area: 'spore', ar: ['الفطر الماشي', 'فطر بوجه ناعس وقبعة منقّطة. ينتفخ ثم ينفخ أبواغاً سامّة إن اقتربت.'], en: ['Walking Shroom', 'A sleepy-faced toadstool with a spotted cap. It swells, then breathes toxic spores when you come close.'] },
  { k: 'jelly', area: 'aqueduct', ar: ['قنديل البحر', 'قنديل شفّاف بقلب مضيء وأهداب بحبّات متوهّجة. يطفو ببطء ولمسته تؤذي.'], en: ['Jelly', 'A clear bell with a glowing heart and beaded tendrils. It floats slowly and hurts to touch.'] },
  { k: 'warden', area: 'crossroads', ar: ['حارس الدرع', 'يحمل درعاً طويلاً مرصّعاً يصدّ كل ضربة من جهة وجهه. اقفز فوقه واضرب ظهره، أو اضربه من الأعلى.'], en: ['Shield Warden', 'It carries a tall studded shield that turns aside any blow from the front. Leap over it and strike its back.'] },
  { k: 'ram', area: 'crossroads', ar: ['النطّاح', 'وحش مشعّر بقرنين مخطّطين. يحفر الأرض ثم يندفع في خط مستقيم، فإن ارتطم بجدار ترنّح.'], en: ['Ram', 'A shaggy beast with ridged horns. It paws the ground, then charges in a line; it is dazed when it hits a wall.'] },
  { k: 'mole', area: 'frost', ar: ['الخلد', 'خلد مغطّى بالصقيع وله مخالب كالمجارف. يحفر ويظهر تحت قدميك؛ وهو مدفون لا يُصاب ولا يؤذي.'], en: ['Frost Mole', 'A frost-furred mole with spade claws. It tunnels and bursts out under your feet; buried, it cannot be hurt or hurt you.'] },
  { k: 'lavaworm', area: 'ember', ar: ['دودة الحمم', 'دودة متوهّجة الفواصل بفم مسنّن وعين ملتهبة. تخرج من أرض سيندرديب فجأة.'], en: ['Lava Worm', 'A worm with glowing seams, a toothed maw and a burning eye. It erupts from the floor of Cinderdeep.'] },
  { k: 'imp', area: 'ember', ar: ['عفريت القنابل', 'عفريت أحمر بقرنين وذيل مسنّن. يحافظ على مسافته ويقذف قنابل تنفجر حلقة نار.'], en: ['Bomb Imp', 'A red imp with horns and a barbed tail. It keeps its distance and lobs bombs that burst in rings of fire.'] },
  { k: 'veil', area: 'frost', ar: ['الحجاب', 'شبح بعباءة وطبقات من الستائر ويدين نحيلتين. يختفي ويظهر بجانبك، ثم يكشف نفسه لحظة بعد ضربته.'], en: ['Veil', 'A cloaked wraith in layers of drapery. It fades and returns beside you, and is exposed for a moment after it strikes.'] },
  { k: 'roller', area: 'ember', ar: ['المدحرج', 'حيوان مدرّع بحلقات تلتف كالكرة الشائكة. لا تصدّه السيوف وهو ملتفّ: اقفز فوقه.'], en: ['Roller', 'An armoured animal that curls into a spiked ball. Blades glance off it while it rolls: jump over it.'] },
  { k: 'slime', area: 'frost', ar: ['الهلام', 'هلام شفّاف بنواة داكنة وفقاعات. ينقسم إلى هلاميتين صغيرتين عند ضربه.'], en: ['Slime', 'A clear jelly with a dark nucleus and bubbles. It splits into two small ones when struck.'] },
  { k: 'chainman', area: 'frost', ar: ['حامل السلسلة', 'حارس ثقيل بخوذة وشقّ للعينين وسلسلة بحلقات وكرة شائكة. يدوّرها بمدى طويل: ابقَ بعيداً أو تحت الكرة.'], en: ['Chain Bearer', 'A heavy guard in a bucket helm with a linked chain and a spiked ball, whirled in a wide arc.'] },
  { k: 'moth', area: 'frost', ar: ['فراشة الليل', 'فراشة بأجنحة ذات عيون وغبار مضيء. تدور حولك ثم تنقضّ، وتضيء ما حولها.'], en: ['Night Moth', 'A moth with eyespotted wings and glowing dust. It circles you, then dives, and lights up its surroundings.'] },
  { k: 'icicle', area: 'frost', ar: ['الجليدة', 'سنّ جليد معلّق بقطرة على رأسه (أو بازلت متوهّج في سيندرديب). ترتجف ثم تسقط فتتحطم وتنمو من جديد.'], en: ['Icicle', 'A hanging spike of ice with a droplet on its tip (or glowing basalt in Cinderdeep). It trembles, falls, shatters and grows back.'] },
  { k: 'heap', area: 'ossuary', ar: ['الكومة', 'كومة عظام ترقد في الأرض حتى تقترب فتنهض هيكلاً بهراوة من عظمة فخذ. إذا هُزم تبقى جمجمته، ثم يعود مرة واحدة: اضرب الجمجمة قبل أن تلتئم.'], en: ['The Heap', 'A mound of bones that lies still until you come near, then rises as a skeleton with a femur for a club. When beaten its skull remains, and it returns once: strike the skull before it knits.'] },
  { k: 'skullbat', area: 'ossuary', ar: ['خفّاش الجمجمة', 'جمجمة بأجنحة من عظام وغشاء رقيق. تحوم فوقك جانباً لجانب ثم تفتح فكّها وتسقط ثلاث أسنان في مروحة.'], en: ['Skull Bat', 'A skull on wings of bone and thin membrane. It hangs above you, drifting side to side, then opens its jaw and drops three teeth in a fan.'] },
  { k: 'censer', area: 'ossuary', ar: ['المبخرة', 'مبخرة على شكل جمجمة تتدلّى من السقف بسلسلة وتتأرجح. إذا رأتك توهّجت ثم نفثت حلقة من الأشباح الخضراء. اضربها حين تقترب من الأرض.'], en: ['The Censer', 'A skull-shaped thurible swinging on a chain from the ceiling. When it sees you it flares and breathes a ring of green wisps. Strike it as it swings near.'] },
  { k: 'lensling', area: 'lunar', ar: ['العدسة الزاحفة', 'خنفساء بنفسجية بعين من زجاج على رقبة قصيرة. تتتبّعك بعدستها ثم تقفلها وتطلق شعاعاً رفيعاً قاتلاً. اخرج من الخط بعد أن يثبت.'], en: ['Lensling', 'A violet bug with an eye of glass on a short neck. Its lens follows you, then locks, and a thin deadly ray follows. Step off the line once it locks.'] },
  { k: 'orrery', area: 'lunar', ar: ['الفلك المصغّر', 'نواة نحاسية بعين واحدة وحلقتين وثلاث كرات تدور حولها. الكرات تجرح من يلمسها؛ اضرب النواة من بين مداراتها.'], en: ['The Orrery', 'A brass core with one eye, two rings and three orbs circling it. The orbs wound whoever touches them; strike the core between their orbits.'] },
  { k: 'lunarhare', area: 'lunar', ar: ['أرنب القمر', 'أرنب فضّي بأذنين طويلتين وهلال على جبينه. ينقبض ثم يقفز نحوك، وفي الجاذبية الضعيفة تصير قفزته طيراناً طويلاً.'], en: ['Lunar Hare', 'A silver hare with long ears and a crescent on its brow. It crouches and leaps at you, and in weak gravity its leap becomes a long flight.'] },
  // ---- bosses
  { k: 'guardian', boss: true, area: 'crossroads', ar: ['الحارس الحجري', 'خنفساء ضخمة بدرع طحلبي متشقق وفكّين وهراوة من قشرة. ينقضّ ويضرب الأرض ويندفع؛ بعد الاندفاع يترنح.'], en: ['Stone Guardian', 'A giant mossy beetle with jaws and a shell mace. It leaps, slams and charges, and is dazed after a charge.'] },
  { k: 'spore', boss: true, area: 'spore', ar: ['أمّ الفطر', 'عفريتة فطر بقبعة حمراء منقّطة وخياشيم ووجه صارم. تنثر الأبواغ وتستدعي مفرزات سامّة.'], en: ['Sporecap Matriarch', 'A toadstool matriarch with a red spotted cap, gills and a stern face. She scatters spores and calls toxic bursts.'] },
  { k: 'weaver', boss: true, area: 'mossgrove', ar: ['حائكة الأشواك', 'فرس نبي رشيقة بجناحين ورقيين ومنجل وإبرة. تقطع بسرعة وتطلق الأشواك وتدور كالعاصفة.'], en: ['Thornweaver', 'A slender mantis with leaf wings, a scythe and a needle. She cuts fast, fires thorns and spins like a storm.'] },
  { k: 'drowned', boss: true, area: 'aqueduct', ar: ['العملاق الغريق', 'غوّاص بخوذة مبرشمة ونافذة زجاجية يظهر وراءها وجه شاحب، ومرساة هائلة. يستدعي فقاعات وينابيع.'], en: ['Drowned Colossus', 'A diver in a riveted helm with a porthole and a pale face behind the glass, and a great anchor.'] },
  { k: 'wraith', boss: true, area: 'crystal', ar: ['شبح البلّور', 'جسم بلّوري متعدد الأوجه بقناع في صدره ونواة مضيئة وشظايا تدور حوله. يطلق ويقفز ويختفي.'], en: ['Crystal Wraith', 'A faceted crystal body with a mask in its chest, a glowing core and orbiting shards.'] },
  { k: 'brood', boss: true, area: 'webbed', ar: ['أمّ الحضنة', 'عنكبوتة هائلة ببطن مرسوم وصغار على ظهرها وستّ عيون وفكّين سامّين. تقفز وتنسج وتستدعي صغارها.'], en: ['Brood Mother', 'A huge spider with a patterned abdomen, spiderlings on her back, six eyes and venomous fangs.'] },
  { k: 'king', boss: true, area: 'throne', ar: ['الملك المجوّف', 'سيّد العرش: درع مضلّع وقناع بتاج من الأشواك وحلقة نورانية في يده. له ثلاثة أطوار.'], en: ['The Hollow King', 'Lord of the throne: ribbed armour, a mask with a crown of spikes and a ring of light in his hand. Three phases.'] },
  { k: 'queen', boss: true, area: 'frost', ar: ['ملكة الصقيع', 'ملكة طافية بثوب جليد مزيّن بالدانتيل وتاج بجواهر. ترمي الشظايا وتنادي الجليد والصواعق.'], en: ['The Rime Queen', 'A floating queen in a gown of lace-like ice and a gemmed crown. She throws shards and calls ice and lightning.'] },
  { k: 'colossus', boss: true, area: 'ember', ar: ['العملاق الجمري', 'عملاق من البازلت المشقّق بوجه منحوت وفرن في صدره. يضرب ويقذف الحمم ويتدحرج ويهزّ الأرض.'], en: ['The Cinder Colossus', 'A giant of cracked basalt with a carved face and a furnace in its chest. It smashes, lobs slag, rolls and shakes the floor.'] },
  { k: 'thunderhoof', boss: true, area: 'stormcrest', ar: ['حافر الرعد', 'ثور عاصفة بدروع وقرون محزّزة وبرق في جلده. ينقضّ ويدكّ الأرض وينادي الصواعق.'], en: ['Thunderhoof', 'A storm bull with plated flanks, ridged horns and lightning in its hide. It charges, stamps and calls thunder.'] },
  { k: 'roc', boss: true, area: 'stormcrest', ar: ['طائر العاصفة', 'طائر هائل بريش رمادي وعين شرسة ومنقار معقوف وعرف من البرق. ينثر الريش وينقضّ ويهبّ بعاصفة.'], en: ['The Storm Roc', 'A great bird with slate feathers, a fierce eye, a hooked beak and a lightning crest. It strafes, dives and raises a gale.'] },
  { k: 'duelist', boss: true, area: 'mirror', ar: ['مبارز الزجاج', 'مبارز بخوذة بريشة ومعطف من الزجاج الأسود وسيف رفيع. يرفع نصله فيصدّ ضرباتك ثم يردّ بطعنة.'], en: ['The Glass Duelist', 'A duelist in a plumed helm, a coat of black glass and a thin rapier. His guard turns your blows, then he ripostes.'] },
  { k: 'twin', boss: true, area: 'mirror', ar: ['توأم الجوّال', 'انعكاسك المظلم بقناع أبيض بقرنين وعينين بنفسجيتين وعباءة سوداء. يقاتل بأدواتك نفسها.'], en: ["The Wanderer's Twin", 'Your dark reflection: a horned white mask, violet eyes, a black cloak. It fights with your own tools.'] },
  { k: 'bonewright', boss: true, area: 'ossuary', ar: ['نحّات العظام', 'هيكل طويل بأربع أذرع ونظّارة نحاسية على جمجمته ومئزر جلدي وإزميل هائل. يكنس الأرض بذراعه ويرمي الأزاميل ويرفع الأعمدة ويستدعي الأكوام.'], en: ['The Bonewright', 'A tall four-armed skeleton with brass goggles on his skull, a leather apron and a great chisel. He sweeps the floor, throws chisels, raises pillars and calls up heaps.'] },
  { k: 'marrow', boss: true, area: 'ossuary', ar: ['طاغية النخاع', 'كل عظام الموتى في جسد واحد بتاج من الجماجم وقلب من نخاع متوهّج. يدكّ الأرض ويمطر الأضلاع ويقبض بقبضته ويبصق النخاع وينادي الأيدي من الأرض.'], en: ['The Marrow Tyrant', 'Every bone of the dead in a single body, a crown of skulls and a heart of glowing marrow. It stamps, rains ribs, smashes with its fist, spits marrow and calls hands from the floor.'] },
  { k: 'stargazer', boss: true, area: 'lunar', ar: ['الراصد', 'فلكي طافٍ بثوب ليلي مرصّع بالنجوم وخوذة نحاسية بعدسة زجاجية ولحية من الضوء ومنظار طويل. يصوّب الأشعة وينزل النيازك ويدير النجوم ويفتح حقلاً من الجاذبية الضعيفة.'], en: ['The Stargazer', 'A floating astronomer in a night robe sewn with stars, a brass lens-helm, a beard of light and a long telescope. He aims rays, calls meteors, spins stars and opens a field of weak gravity.'] },
  { k: 'regent', boss: true, area: 'lunar', ar: ['وصيّ الكسوف', 'ملك أسود الثوب بقناع فضي وتاج من الأشعة وقرص معتم خلفه بهالة من الجمر. يرسل الهلال والبدر والكسوف ويغرق القاعة بالظلام ويخفض الجاذبية ثم يدير أشعته كمصباح كاشف.'], en: ['The Eclipse Regent', 'A king in black with a silver mask, a crown of rays and a dark disc behind him ringed with corona. He sends crescents, the full moon and the eclipse, drowns the hall in darkness, drops gravity, then sweeps his rays like a searchlight.'] },
];
const BESTIARY_INDEX = {}; BESTIARY.forEach((b, i) => { BESTIARY_INDEX[(b.boss ? 'b:' : 'e:') + b.k] = i; });
function bestiaryKey(e) { if (e.isBoss) return 'b:' + e.bossKey; const k = e.kind === 'slimelet' ? 'slime' : e.kind === 'brood_child' ? 'spider' : e.kind; return BESTIARY_INDEX['e:' + k] !== undefined ? 'e:' + k : null; }
const bestiaryName = b => b[LANG.cur === 'ar' ? 'ar' : 'en'][0];
const bestiaryDesc = b => b[LANG.cur === 'ar' ? 'ar' : 'en'][1];
