'use strict';
// Arabic / English strings. Default language is Arabic; toggle with L on the title screen.
const LANG = { cur: 'ar' };
try { const l = localStorage.getItem('duskwell_lang'); if (l === 'en' || l === 'ar') LANG.cur = l; } catch (e) { /* storage blocked */ }

const STR = {
  ar: {
    title: 'أرض الغسق', subtitle: 'مملكة سقط نورها في الأعماق',
    press: 'اضغط Z أو Enter للبدء', cont: 'متابعة', newgame: 'لعبة جديدة', lang: 'English',
    confirmNew: 'سيُحذف التقدم المحفوظ. متأكد؟', yes: 'نعم', no: 'لا',
    pause: 'إيقاف مؤقت', resume: 'متابعة', map: 'الخريطة', sound: 'الصوت', on: 'يعمل', off: 'متوقف', quit: 'العودة للقائمة',
    controls: 'الأزرار', ctl: '← → حركة   Z قفز   X ضربة   C اندفاع   F كرة روح / شفاء (مطولاً)   ↓+F انقضاض   Q شهاب (مطولاً)   ↑ تفاعل   Tab خريطة',
    geo: 'جيو', soul: 'الروح', youDied: 'سقطتَ في الظلام', shadowHere: 'ظلّك ينتظر حيث سقطت',
    saved: 'تم الحفظ', rest: 'استرح', talk: 'تحدّث', read: 'اقرأ', buy: 'شراء', soldout: 'نفد', price: 'جيو',
    shopTitle: 'التاجر الغريب', leave: 'مغادرة', noGeo: 'لا يكفي الجيو',
    itemMask: 'قناع إضافي', itemNail: 'نصل مشحوذ', itemSoul: 'قلب الروح',
    itemMaskD: 'يزيد صحتك القصوى بواحد', itemNailD: 'ضربتك تؤذي أكثر', itemSoulD: 'كل ضربة تملأ روحاً أكثر',
    shadowKilled: 'استعدتَ الجيو من ظلّك',
    abil_dash: 'اندفاع الظل', abil_dash_d: 'اضغط C لتنطلق بسرعة. يمكنك الاندفاع في الهواء مرة واحدة.',
    abil_wall: 'مخلب الجدار', abil_wall_d: 'التصق بالجدران واقفز عنها بالضغط على Z.',
    abil_double: 'أجنحة الغسق', abil_double_d: 'اضغط Z مرة ثانية في الهواء للقفز قفزة إضافية.',
    seed: 'بذرة القناع', seed_d: 'صحتك القصوى زادت بواحد.',
    cache: 'كنز مخبّأ', cache_d: 'وجدتَ كمية من الجيو.',
    area_hushvale: 'وادي الهمس', area_crossroads: 'مفترق الأعماق', area_mossgrove: 'بستان الطحلب',
    area_crystal: 'أبراج البلّور', area_throne: 'العرش المجوّف',
    boss_guardian: 'الحارس الحجري', boss_weaver: 'حائكة الأشواك', boss_wraith: 'شبح البلّور', boss_king: 'الملك المجوّف',
    endTitle: 'انتهت الرحلة', endText: 'خمد صدى العرش المجوّف، وعاد للمملكة بصيص نور.',
    endStats: 'الوقت', deaths: 'مرات السقوط', masks: 'الأقنعة', thanks: 'شكراً للعب. اضغط Z للعودة إلى القائمة.',
    sign_controls: 'لافتة: ← → للحركة، Z للقفز (اضغط مطولاً لقفزة أعلى)، X للضرب (مع ↑ أو ↓ لتغيير الاتجاه)، F كرة روح، واضغط F مطولاً للشفاء. ↑ عند المقعد للجلوس والحفظ. البئر في أقصى اليمين.',
    elder1: 'الشيخ: كان نور المملكة يسكن الأعماق قبل أن ينطفئ. نزل الملك المجوّف يبحث عنه فلم يعد.',
    elder2: 'الشيخ: اضرب الأعداء لتجمع الروح، ثم استعملها لتشفي جراحك. وإذا سقطتَ فسيحرس ظلّك ما معك من جيو.',
    elder3: 'الشيخ: ستّة حرّاس يحملون أختام بوابة العرش، وكلٌّ منهم يحفظ قوة تحتاجها. انزل البئر وابدأ.',
    merchant: 'التاجر: هل معك جيو؟ عندي ما يساعدك في العتمة.',
    trap: 'تحذير: أنت في ساحة معركة. لا مفرّ حتى النهاية.',
    abil_superdash: 'قلب الشهاب', abil_superdash_d: 'على الأرض أو متشبّثاً بجدار: اضغط Q (أو زر الشهاب) مطوّلاً حتى يومض، ثم اتركه لتنطلق كالشهاب. القفز يوقفك.',
    area_frost: 'قمم الصقيع', area_ember: 'أعماق الجمر',
    sign_to_frost: 'لافتة: شرقاً قمم الصقيع. تقطعها حفرة عريضة لا يعبرها إلا من يندفع.',
    sign_to_ember: 'لافتة: غرباً أعماق الجمر. الحمم تتدفق هناك، ومن لا يتسلق الجدران يعود أدراجه.',
    sign_frost: 'لافتة: الجليد زلق. من يتمهّل يعبر، ومن يركض ينزلق.',
    sign_frost_queen: 'لافتة: ملكة الصقيع تنتظر خلف هذا الباب. اجلس على المقعد أولاً.',
    sign_ember: 'لافتة: الحمم تحرق. لا تلمسها.',
    sign_ember_colossus: 'لافتة: قلب الفرن يخفق خلف هذا الباب. العملاق الجمري لا يرحم.',
    boss_queen: 'ملكة الصقيع', boss_colossus: 'العملاق الجمري',
    area_stormcrest: 'ذرى العاصفة', area_mirror: 'قبو المرايا',
    bestiary: 'الموسوعة', bestiaryNew: 'دخل الموسوعة: ', bestiaryHint: '← → تصفّح    Esc: رجوع', bestiaryUnknown: 'لم تلتقِ به بعد', hp: 'الصحة', boss: 'زعيم', foes: 'المخلوقات',
    sign_storm: 'لافتة: الريح هنا حيّة. ادخل التيار الصاعد فيرفعك، واحذر التي تدفعك إلى الهاوية.',
    sign_storm_bridge: 'لافتة: جسر الرعد. الريح خلفك تدفعك أسرع مما تريد، والريح أمامك تعيدك.',
    sign_storm_roc: 'لافتة: عشّ طائر العاصفة خلف هذا الباب. اجلس على المقعد أولاً.',
    sign_mirror: 'لافتة: المرايا هنا تحفظ وجوه من مرّوا. لا تطل النظر في الفضّة السائلة، فهي تحرق.',
    sign_mirror_twin: 'لافتة: خلف هذا الباب من يشبهك. اجلس على المقعد أولاً.',
    boss_thunderhoof: 'حافر الرعد', boss_roc: 'طائر العاصفة', boss_duelist: 'مبارز الزجاج', boss_twin: 'توأم الجوّال',
    area_rustworks: 'ورشة الصدأ', gate_opened: 'دوّى صوت بوابةٍ تنفتح.',
    sign_rust: 'لافتة: ورشة الصدأ. الألواح المتآكلة لا تحتمل الوقوف طويلاً.',
    sign_lever: 'لافتة: الذراع يوقظ الآلات ويفتح باب الورشة. اضربه.',
    sign_comet: 'لافتة: لا جسر هنا. قلّة عبروا، وكلهم كانوا كالشهاب.',
    abil_dive: 'انقضاض الروح', abil_dive_d: 'في الهواء: اضغط ↓ مع F لتنقضّ للأسفل. تكسر الأرضيات المتشققة وتضرب ما حولك.',
    fang: 'ناب الحضنة', fang_d: 'نصلك صار أشدّ فتكاً.',
    seal_gate: 'بوابة العرش مختومة. أحضر أختام الحرّاس الستة.',
    area_spore: 'كهوف الأبواغ', area_aqueduct: 'القناة الغارقة', area_webbed: 'الأعماق المنسوجة',
    boss_spore: 'أمّ الفطر', boss_drowned: 'العملاق الغريق', boss_brood: 'أمّ الحضنة',
    sign_spore: 'لافتة: قبعات الفطر الحمراء تقذفك عالياً. اهبط عليها.',
    sign_crack: 'لافتة: الأرض هنا متشققة. شيءٌ أثقل من الخطى يمكنه كسرها.',
    sign_acid: 'لافتة: الماء الأخضر حمضٌ يحرق. لا تلمسه.',
    gfx: 'الرسوم',
    charms: 'التمائم', cost: 'الفتحات', notches: 'الفتحات', worn: 'مرتداة', noCharms: 'لم تجد أي تميمة بعد. ابحث في الزوايا البعيدة، واسأل التاجر.',
    charmsHint: 'Z: ارتداء أو نزع    Esc: رجوع', charmsBench: 'تُغيَّر التمائم وأنت جالس على مقعد فقط.', charmsFull: 'أنت مُثقَل بالتمائم أصلاً: انزع شيئاً أولاً.',
    overcharm: 'تميمة فوق الفتحات! كل إصابة ستكلّفك الضعف.', charm_found_d: 'اجلس على مقعد وافتح التمائم من قائمة الإيقاف لترتديها.',
    itemNotch: 'فتحة تميمة', itemNotchD: 'تتسع لتمائم أكثر',
    stationTitle: 'محطات الفانوس', stationFare: 'أجرة الرحلة', stationLit: 'أُضيئت محطة الفانوس. يمكنك الآن السفر إليها.', stationNone: 'لا توجد محطة مضاءة أخرى بعد. أشعل محطات الفانوس في المناطق الأخرى.',
    travel: 'سافر', light: 'أشعل',
    itemNail2: 'نصل مسنون', itemNail3: 'نصل الغسق',
    itemWail: 'مخطوطة النداء', itemWailD: 'تعلّم نداء الغسق: عمود نور فوقك (↑ + F)',
    abil_wail: 'نداء الغسق', abil_wail_d: 'اضغط ↑ مع F لتطلق عمود نور فوقك يضرب كل ما فيه عدة مرات. يكلّف روحاً مثل بقية التعاويذ.',
  },
  en: {
    title: 'DUSKWELL', subtitle: 'A kingdom whose light fell into the deep',
    press: 'Press Z or Enter to begin', cont: 'Continue', newgame: 'New Game', lang: 'العربية',
    confirmNew: 'Saved progress will be erased. Sure?', yes: 'Yes', no: 'No',
    pause: 'Paused', resume: 'Resume', map: 'Map', sound: 'Sound', on: 'On', off: 'Off', quit: 'Back to Title',
    controls: 'Controls', ctl: 'Arrows move   Z jump   X strike   C dash   F soul bolt / heal (hold)   Down+F dive   Q comet (hold)   Up interact   Tab map',
    geo: 'Geo', soul: 'Soul', youDied: 'You fell into the dark', shadowHere: 'Your shade waits where you fell',
    saved: 'Saved', rest: 'Rest', talk: 'Talk', read: 'Read', buy: 'Buy', soldout: 'Sold out', price: 'Geo',
    shopTitle: 'The Odd Merchant', leave: 'Leave', noGeo: 'Not enough Geo',
    itemMask: 'Extra Mask', itemNail: 'Honed Nail', itemSoul: 'Soul Heart',
    itemMaskD: 'Raises max health by one', itemNailD: 'Your strike hurts more', itemSoulD: 'Each strike gathers more soul',
    shadowKilled: 'You took your Geo back from your shade',
    abil_dash: 'Shadow Dash', abil_dash_d: 'Press C to surge forward. You can dash once in mid-air.',
    abil_wall: 'Wall Claw', abil_wall_d: 'Cling to walls and leap off them with Z.',
    abil_double: 'Dusk Wings', abil_double_d: 'Press Z again in mid-air for an extra jump.',
    seed: 'Mask Seed', seed_d: 'Your maximum health rose by one.',
    cache: 'Hidden Cache', cache_d: 'You found a stash of Geo.',
    area_hushvale: 'Hushvale', area_crossroads: 'Sunken Crossroads', area_mossgrove: 'Mossgrove',
    area_crystal: 'Crystal Spires', area_throne: 'The Hollow Throne',
    boss_guardian: 'Stone Guardian', boss_weaver: 'Thornweaver', boss_wraith: 'Crystal Wraith', boss_king: 'The Hollow King',
    endTitle: 'The Journey Ends', endText: 'The echo of the Hollow Throne fades, and a glimmer of light returns to the kingdom.',
    endStats: 'Time', deaths: 'Falls', masks: 'Masks', thanks: 'Thanks for playing. Press Z to return to the title.',
    sign_controls: 'Sign: Arrows move, Z jumps (hold for height), X strikes (with Up or Down to aim), F casts a soul bolt, hold F to heal. Press Up at a bench to rest and save. The well is at the far right.',
    elder1: 'Elder: The kingdom\'s light lived in the deep until it went out. The Hollow King descended to find it and never returned.',
    elder2: 'Elder: Strike foes to gather soul, then spend it to mend your wounds. If you fall, your shade will guard your Geo.',
    elder3: 'Elder: Six guardians hold the seals of the throne gate, and each keeps a power you will need. Go down the well.',
    merchant: 'Merchant: Got any Geo? I have things that help in the dark.',
    trap: 'Warning: this is a battle arena. There is no way out until the end.',
    abil_superdash: 'Comet Heart', abil_superdash_d: 'On the ground or clinging to a wall, hold Q (or the Comet button) until it flashes, then let go to blaze forward. Jump to stop.',
    area_frost: 'Rimecrest', area_ember: 'Cinderdeep',
    sign_to_frost: 'Sign: east lies Rimecrest. A wide pit cuts the way; only those who dash cross it.',
    sign_to_ember: 'Sign: west lies Cinderdeep. Lava runs there, and those who cannot climb walls turn back.',
    sign_frost: 'Sign: the ice is slippery. Those who go slowly cross; those who run slide.',
    sign_frost_queen: 'Sign: the Rime Queen waits behind this door. Rest on the bench first.',
    sign_ember: 'Sign: lava burns. Do not touch it.',
    sign_ember_colossus: 'Sign: the Furnace Heart beats behind this door. The Cinder Colossus shows no mercy.',
    boss_queen: 'The Rime Queen', boss_colossus: 'The Cinder Colossus',
    area_stormcrest: 'Stormcrest', area_mirror: 'Mirror Vault',
    bestiary: 'Bestiary', bestiaryNew: 'Added to the bestiary: ', bestiaryHint: 'Left / Right: browse    Esc: back', bestiaryUnknown: 'Not met yet', hp: 'Health', boss: 'Boss', foes: 'Creatures',
    sign_storm: 'Sign: the wind here is alive. Step into an updraft and it will lift you; beware the ones that push you toward the pit.',
    sign_storm_bridge: 'Sign: the Thunder Bridge. The wind behind you pushes faster than you want; the wind ahead pushes you back.',
    sign_storm_roc: 'Sign: the Storm Roc nests behind this door. Rest on the bench first.',
    sign_mirror: 'Sign: the mirrors here keep the faces of those who passed. Do not linger by the quicksilver: it burns.',
    sign_mirror_twin: 'Sign: behind this door waits one who looks like you. Rest on the bench first.',
    boss_thunderhoof: 'Thunderhoof', boss_roc: 'The Storm Roc', boss_duelist: 'The Glass Duelist', boss_twin: "The Wanderer's Twin",
    area_rustworks: 'The Rustworks', gate_opened: 'Somewhere, a gate grinds open.',
    sign_rust: 'Sign: The Rustworks. The corroded plates will not hold you for long.',
    sign_lever: 'Sign: The lever wakes the machines and opens the works. Strike it.',
    sign_comet: 'Sign: There is no bridge here. Few have crossed, and all of them moved like comets.',
    abil_dive: 'Soul Dive', abil_dive_d: 'In the air, hold Down and press F to plunge. It breaks cracked floors and strikes everything around you.',
    fang: 'Brood Fang', fang_d: 'Your nail cuts deeper.',
    seal_gate: 'The throne gate is sealed. Bring the seals of the six guardians.',
    area_spore: 'Spore Hollows', area_aqueduct: 'Sunken Aqueduct', area_webbed: 'Webbed Depths',
    boss_spore: 'Sporecap Matriarch', boss_drowned: 'Drowned Colossus', boss_brood: 'Brood Mother',
    sign_spore: 'Sign: The red mushroom caps throw you high. Land on them.',
    sign_crack: 'Sign: The ground here is cracked. Something heavier than footsteps could break it.',
    sign_acid: 'Sign: The green water is acid. Do not touch it.',
    gfx: 'Graphics',
    charms: 'Charms', cost: 'Notches', notches: 'Notches', worn: 'Worn', noCharms: 'You have found no charms yet. Search the far corners, and ask the merchant.',
    charmsHint: 'Z: wear or remove    Esc: back', charmsBench: 'Charms can only be changed while resting on a bench.', charmsFull: 'You are already overcharmed: remove something first.',
    overcharm: 'Over the notch limit! Every wound will cost you double.', charm_found_d: 'Rest on a bench and open Charms from the pause menu to wear it.',
    itemNotch: 'Charm Notch', itemNotchD: 'Room for more charms',
    stationTitle: 'Lantern Stations', stationFare: 'Fare', stationLit: 'The lantern station is lit. You can now travel to it.', stationNone: 'No other station is lit yet. Light the lantern stations in the other areas.',
    travel: 'Travel', light: 'Light',
    itemNail2: 'Keen Nail', itemNail3: 'Duskforged Nail',
    itemWail: 'Cry Scroll', itemWailD: 'Learn the Dusk Cry: a column of light above you (Up + F)',
    abil_wail: 'Dusk Cry', abil_wail_d: 'Hold Up and press F to loose a column of light above you that strikes everything in it several times. It costs soul like the other spells.',
  },
};
function tr(k) { return (STR[LANG.cur] && STR[LANG.cur][k]) || STR.en[k] || k; }
function setLang(l) { LANG.cur = l; try { localStorage.setItem('duskwell_lang', l); } catch (e) { /* ignore */ } if (window.refreshTouchLabels) window.refreshTouchLabels(); }
const FONT_AR = '"Cairo","Noto Naskh Arabic","Segoe UI",Tahoma,sans-serif';
const FONT_EN = '"Cinzel","Trajan Pro","Palatino Linotype",Georgia,serif';
function font(px, weight) { return (weight || '700') + ' ' + px + 'px ' + (LANG.cur === 'ar' ? FONT_AR : FONT_EN); }
